// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiT3ehOSMUch3lo8jnfqVEzQNQQNpSUw4',
    appId: '1:511657699751:web:da0a626aad542581cfee82',
    messagingSenderId: '511657699751',
    projectId: 'plant-notebook',
    authDomain: 'plant-notebook.firebaseapp.com',
    storageBucket: 'plant-notebook.firebasestorage.app',
    measurementId: 'G-71YRSBSQ1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPDGGPENh6Koey0Mutubl0yQhcNILFiN8',
    appId: '1:511657699751:android:4df644f3b2448b91cfee82',
    messagingSenderId: '511657699751',
    projectId: 'plant-notebook',
    storageBucket: 'plant-notebook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi5o3k32jrBFI3KcWEZL5Z9AP3t_e2j3E',
    appId: '1:511657699751:ios:00dafae06ee7cba5cfee82',
    messagingSenderId: '511657699751',
    projectId: 'plant-notebook',
    storageBucket: 'plant-notebook.firebasestorage.app',
    androidClientId: '511657699751-b9otkaj19vurgvf99v19o8s7td2lk962.apps.googleusercontent.com',
    iosClientId: '511657699751-pi7m0eosm1bumo4m9bl8qeb6iv9hf8v2.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantNotebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi5o3k32jrBFI3KcWEZL5Z9AP3t_e2j3E',
    appId: '1:511657699751:ios:00dafae06ee7cba5cfee82',
    messagingSenderId: '511657699751',
    projectId: 'plant-notebook',
    storageBucket: 'plant-notebook.firebasestorage.app',
    androidClientId: '511657699751-b9otkaj19vurgvf99v19o8s7td2lk962.apps.googleusercontent.com',
    iosClientId: '511657699751-pi7m0eosm1bumo4m9bl8qeb6iv9hf8v2.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantNotebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiT3ehOSMUch3lo8jnfqVEzQNQQNpSUw4',
    appId: '1:511657699751:web:264ace322885951ccfee82',
    messagingSenderId: '511657699751',
    projectId: 'plant-notebook',
    authDomain: 'plant-notebook.firebaseapp.com',
    storageBucket: 'plant-notebook.firebasestorage.app',
    measurementId: 'G-HQLKBZYRQQ',
  );
}
